version: '3'

services:
  django_db:
    image: postgres
    environment:
      POSTGRES_USER: delFlindmusaceIGHteaL
      POSTGRES_PASSWORD: hhWkL1OrCZNzhXl9eQH4L537
      POSTGRES_DB: dev_django_db
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: ps_data